#include "Case2D_Matlab.h"

#include <fstream>
#include <stdexcept>

namespace Case2DMatlab {

void WriteNoFracPTValidationPlotScript(const ValidationPlotScriptSpec& spec) {
    std::ofstream out(spec.script_path.c_str(), std::ios::out | std::ios::trunc);
    if (!out.good()) {
        throw std::runtime_error("[Case2DMatlab] failed to write MATLAB plot script: " + spec.script_path);
    }

    out <<
"rootDir = fileparts(mfilename('fullpath'));\n"
"if isempty(rootDir)\n"
"    rootDir = pwd;\n"
"end\n"
"figDir = fullfile(rootDir, 'figures');\n"
"if ~exist(figDir, 'dir')\n"
"    mkdir(figDir);\n"
"end\n"
"\n"
"families = {";

    for (std::size_t i = 0; i < spec.profile_families.size(); ++i) {
        if (i != 0) out << ", ";
        out << "'" << spec.profile_families[i] << "'";
    }

    out <<
"};\n"
"finalTag = '" << spec.final_tag << "';\n"
"\n"
"for iFam = 1:numel(families)\n"
"    fam = families{iFam};\n"
"    cmpFile = fullfile(rootDir, ['compare_profile_' fam '_' finalTag '.csv']);\n"
"    if ~isfile(cmpFile)\n"
"        warning('Skipping final profile plot because file is missing: %s', cmpFile);\n"
"        continue;\n"
"    end\n"
"    tbl = readtable(cmpFile);\n"
"    f = figure('Color', 'w', 'Position', [100 100 1200 420]);\n"
"    subplot(1,2,1);\n"
"    plot(tbl.target_axis_m, tbl.p_num_pa, 'LineWidth', 1.6); hold on;\n"
"    plot(tbl.target_axis_m, tbl.p_ref_pa, '--', 'LineWidth', 1.6);\n"
"    xlabel('Target Axis (m)'); ylabel('Pressure (Pa)');\n"
"    title(['Pressure Compare: ' strrep(fam, '_', ' ') ' (Final)']);\n"
"    legend({'Engineering', 'Reference'}, 'Location', 'best'); grid on; box on;\n"
"    subplot(1,2,2);\n"
"    plot(tbl.target_axis_m, tbl.t_num_k, 'LineWidth', 1.6); hold on;\n"
"    plot(tbl.target_axis_m, tbl.t_ref_k, '--', 'LineWidth', 1.6);\n"
"    xlabel('Target Axis (m)'); ylabel('Temperature (K)');\n"
"    title(['Temperature Compare: ' strrep(fam, '_', ' ') ' (Final)']);\n"
"    legend({'Engineering', 'Reference'}, 'Location', 'best'); grid on; box on;\n"
"    exportgraphics(f, fullfile(figDir, ['profile_compare_' fam '.pdf']), 'ContentType', 'vector');\n"
"    exportgraphics(f, fullfile(figDir, ['profile_compare_' fam '.png']), 'Resolution', 300);\n"
"    close(f);\n"
"end\n"
"\n"
"monitorFile = fullfile(rootDir, 'compare_monitor_timeseries.csv');\n"
"if isfile(monitorFile)\n"
"    mon = readtable(monitorFile);\n"
"    labelsP = mon.Properties.VariableNames(startsWith(mon.Properties.VariableNames, 'p_num_'));\n"
"    labelsT = mon.Properties.VariableNames(startsWith(mon.Properties.VariableNames, 't_num_'));\n"
"    f = figure('Color', 'w', 'Position', [120 120 1200 460]);\n"
"    subplot(1,2,1); hold on;\n"
"    for i = 1:numel(labelsP)\n"
"        refName = strrep(labelsP{i}, 'p_num_', 'p_ref_');\n"
"        plot(mon.target_time_s, mon.(labelsP{i}), 'LineWidth', 1.2);\n"
"        if ismember(refName, mon.Properties.VariableNames)\n"
"            plot(mon.target_time_s, mon.(refName), '--', 'LineWidth', 1.0);\n"
"        end\n"
"    end\n"
"    xlabel('Time (s)'); ylabel('Pressure (Pa)'); title('Monitor Compare: Pressure'); grid on; box on;\n"
"    subplot(1,2,2); hold on;\n"
"    for i = 1:numel(labelsT)\n"
"        refName = strrep(labelsT{i}, 't_num_', 't_ref_');\n"
"        plot(mon.target_time_s, mon.(labelsT{i}), 'LineWidth', 1.2);\n"
"        if ismember(refName, mon.Properties.VariableNames)\n"
"            plot(mon.target_time_s, mon.(refName), '--', 'LineWidth', 1.0);\n"
"        end\n"
"    end\n"
"    xlabel('Time (s)'); ylabel('Temperature (K)'); title('Monitor Compare: Temperature'); grid on; box on;\n"
"    exportgraphics(f, fullfile(figDir, 'monitor_compare.pdf'), 'ContentType', 'vector');\n"
"    exportgraphics(f, fullfile(figDir, 'monitor_compare.png'), 'Resolution', 300);\n"
"    close(f);\n"
"end\n"
"\n"
"gridFile = fullfile(rootDir, 'grid_convergence.csv');\n"
"if isfile(gridFile)\n"
"    gridTbl = sortrows(readtable(gridFile), 'h_char', 'descend');\n"
"    f = figure('Color', 'w', 'Position', [140 140 1000 420]);\n"
"    subplot(1,2,1);\n"
"    plot(gridTbl.h_char, gridTbl.pressure_cell_l2_norm, '-o', 'LineWidth', 1.6); hold on;\n"
"    plot(gridTbl.h_char, gridTbl.temperature_horizontal_l2_norm, '-s', 'LineWidth', 1.6);\n"
"    set(gca, 'XDir', 'reverse'); xlabel('Characteristic Grid Size'); ylabel('Normalized L2');\n"
"    title('Grid Convergence: Pressure Cell / Temperature Horizontal');\n"
"    legend({'Pressure cell', 'Temperature profile'}, 'Location', 'best'); grid on; box on;\n"
"    subplot(1,2,2);\n"
"    plot(gridTbl.h_char, gridTbl.pressure_order, '-o', 'LineWidth', 1.6); hold on;\n"
"    plot(gridTbl.h_char, gridTbl.temperature_order, '-s', 'LineWidth', 1.6);\n"
"    set(gca, 'XDir', 'reverse'); xlabel('Characteristic Grid Size'); ylabel('Observed Order');\n"
"    title('Grid Convergence: Observed Order');\n"
"    legend({'Pressure', 'Temperature'}, 'Location', 'best'); grid on; box on;\n"
"    exportgraphics(f, fullfile(figDir, 'grid_convergence.pdf'), 'ContentType', 'vector');\n"
"    exportgraphics(f, fullfile(figDir, 'grid_convergence.png'), 'Resolution', 300);\n"
"    close(f);\n"
"end\n"
"\n"
"timeFile = fullfile(rootDir, 'time_sensitivity.csv');\n"
"if isfile(timeFile)\n"
"    timeTbl = sortrows(readtable(timeFile), 'dt_init', 'descend');\n"
"    pTimeCol = 'pressure_time_self_l2_norm';\n"
"    tTimeCol = 'temperature_time_self_l2_norm';\n"
"    if ~ismember(pTimeCol, timeTbl.Properties.VariableNames)\n"
"        pTimeCol = 'pressure_horizontal_l2_norm';\n"
"    end\n"
"    if ~ismember(tTimeCol, timeTbl.Properties.VariableNames)\n"
"        tTimeCol = 'temperature_horizontal_l2_norm';\n"
"    end\n"
"    f = figure('Color', 'w', 'Position', [160 160 1000 420]);\n"
"    subplot(1,2,1);\n"
"    plot(timeTbl.dt_init, timeTbl.(pTimeCol), '-o', 'LineWidth', 1.6); hold on;\n"
"    plot(timeTbl.dt_init, timeTbl.(tTimeCol), '-s', 'LineWidth', 1.6);\n"
"    set(gca, 'XDir', 'reverse'); xlabel('Initial Time Step (s)'); ylabel('Normalized L2');\n"
"    title('Time Sensitivity: Error Metric');\n"
"    legend({'Pressure', 'Temperature'}, 'Location', 'best'); grid on; box on;\n"
"    subplot(1,2,2);\n"
"    plot(timeTbl.dt_init, timeTbl.pressure_order, '-o', 'LineWidth', 1.6); hold on;\n"
"    plot(timeTbl.dt_init, timeTbl.temperature_order, '-s', 'LineWidth', 1.6);\n"
"    set(gca, 'XDir', 'reverse'); xlabel('Initial Time Step (s)'); ylabel('Observed Order');\n"
"    title('Time Sensitivity: Observed Order');\n"
"    legend({'Pressure', 'Temperature'}, 'Location', 'best'); grid on; box on;\n"
"    exportgraphics(f, fullfile(figDir, 'time_sensitivity.pdf'), 'ContentType', 'vector');\n"
"    exportgraphics(f, fullfile(figDir, 'time_sensitivity.png'), 'Resolution', 300);\n"
"    close(f);\n"
"end\n"
"\n"
"summaryFile = fullfile(rootDir, 'validation_summary.csv');\n"
"if isfile(summaryFile)\n"
"    sumTbl = readtable(summaryFile);\n"
"    vals = [sumTbl.final_pressure_cell_l2_norm(1), sumTbl.final_temperature_horizontal_l2_norm(1), ...\n"
"        sumTbl.final_monitor_temperature_l2_norm(1), sumTbl.final_pressure_vertical_uniformity_norm_std(1), ...\n"
"        sumTbl.final_temperature_vertical_uniformity_norm_std(1)];\n"
"    f = figure('Color', 'w', 'Position', [180 180 820 420]);\n"
"    bar(categorical({'p cell L2', 'T profile L2', 'T monitor L2', 'p vertical std', 'T vertical std'}), vals);\n"
"    ylabel('Metric Value'); title('Validation Metric Dashboard'); grid on; box on;\n"
"    exportgraphics(f, fullfile(figDir, 'validation_dashboard.pdf'), 'ContentType', 'vector');\n"
"    exportgraphics(f, fullfile(figDir, 'validation_dashboard.png'), 'Resolution', 300);\n"
"    close(f);\n"
"end\n"
"\n"
"for iFam = 1:numel(families)\n"
"    cmpFile = fullfile(rootDir, ['compare_profile_' families{iFam} '_' finalTag '.csv']);\n"
"    if ~isfile(cmpFile)\n"
"        continue;\n"
"    end\n"
"    tbl = readtable(cmpFile);\n"
"    f = figure('Color', 'w', 'Position', [200 200 980 420]);\n"
"    subplot(1,2,1);\n"
"    scatter(tbl.p_ref_pa, tbl.p_num_pa, 18, 'filled'); hold on;\n"
"    minP = min([tbl.p_ref_pa; tbl.p_num_pa]); maxP = max([tbl.p_ref_pa; tbl.p_num_pa]);\n"
"    plot([minP maxP], [minP maxP], 'k--', 'LineWidth', 1.0);\n"
"    xlabel('Reference Pressure (Pa)'); ylabel('Engineering Pressure (Pa)'); title('Parity Plot: Pressure'); grid on; box on;\n"
"    subplot(1,2,2);\n"
"    scatter(tbl.t_ref_k, tbl.t_num_k, 18, 'filled'); hold on;\n"
"    minT = min([tbl.t_ref_k; tbl.t_num_k]); maxT = max([tbl.t_ref_k; tbl.t_num_k]);\n"
"    plot([minT maxT], [minT maxT], 'k--', 'LineWidth', 1.0);\n"
"    xlabel('Reference Temperature (K)'); ylabel('Engineering Temperature (K)'); title('Parity Plot: Temperature'); grid on; box on;\n"
"    exportgraphics(f, fullfile(figDir, ['parity_' families{iFam} '.pdf']), 'ContentType', 'vector');\n"
"    exportgraphics(f, fullfile(figDir, ['parity_' families{iFam} '.png']), 'Resolution', 300);\n"
"    close(f);\n"
"end\n";
}

} // namespace Case2DMatlab
