#include "CaseCommon_Skeleton.h"

#include <fstream>
#include <stdexcept>

namespace CaseCommon {
namespace {

void WriteTextFile(const std::string& path, const std::string& text) {
    std::ofstream out(path.c_str(), std::ios::out | std::ios::trunc);
    if (!out.good()) {
        throw std::runtime_error("[CaseSkeleton] failed to write file: " + path);
    }
    out << text;
}

std::string JoinNotes(const std::vector<std::string>& notes) {
    std::string out;
    for (const auto& note : notes) {
        out += "- " + note + "\n";
    }
    return out;
}

} // namespace

CaseArtifactPaths PrepareSkeletonArtifacts(const SkeletonTemplateContext& ctx, CaseStage stage) {
    const CaseArtifactPaths artifacts = BuildArtifactPaths(ctx.output_root, ctx.case_code, ctx.case_slug);

    EnsureDirRecursive(artifacts.case_dir);
    EnsureDirRecursive(artifacts.studies_dir);
    EnsureDirRecursive(artifacts.figures_dir);
    EnsureDirRecursive(artifacts.engineering_dir);
    EnsureDirRecursive(artifacts.reference_dir);
    EnsureDirRecursive(artifacts.report_dir);
    EnsureDirRecursive(artifacts.report_scripts_dir);

    std::string report;
    report += "# " + ctx.case_code + " template skeleton\n\n";
    report += "- Title: `" + ctx.title + "`\n";
    report += "- Stage: `" + std::string(ToString(stage)) + "`\n";
    report += "- Case slug: `" + ctx.case_slug + "`\n";
    report += "- Status: `skeleton`\n\n";
    if (!ctx.notes.empty()) {
        report += "## Notes\n";
        report += JoinNotes(ctx.notes);
        report += "\n";
    }
    report += "## Artifact contract\n";
    report += "- `studies/` for grid/dt studies and validation tables\n";
    report += "- `figures/` for final exported figures only\n";
    report += "- `engineering/` for solver-side raw outputs and reference specs\n";
    report += "- `reference/` for COMSOL or analytical reference payloads\n";
    report += "- `report/` for summaries and Matlab scripts\n";
    WriteTextFile(artifacts.report_status_markdown_path, report);

    std::string engineering;
    engineering += "stage=" + std::string(ToString(stage)) + "\n";
    engineering += "case_code=" + ctx.case_code + "\n";
    engineering += "case_slug=" + ctx.case_slug + "\n";
    engineering += "status=skeleton\n";
    WriteTextFile(artifacts.engineering_stage_manifest_path, engineering);

    std::string reference;
    reference += "reference_mode=external_weak_coupling\n";
    reference += "expected_writer=java_or_ps1_wrapper\n";
    reference += "status=pending\n";
    WriteTextFile(artifacts.reference_contract_path, reference);

    std::string scriptStub;
    scriptStub += "% " + ctx.case_code + " Matlab script placeholder\n";
    scriptStub += "% Generated by template skeleton bootstrap.\n";
    WriteTextFile(artifacts.report_scripts_dir + "/README.m", scriptStub);

    return artifacts;
}

[[noreturn]] void ThrowStageNotImplemented(const SkeletonTemplateContext& ctx,
                                          CaseStage stage,
                                          const std::string& detail) {
    throw std::runtime_error(
        "[CaseSkeleton] " + ctx.case_code + " (" + ctx.title + ") stage `" +
        std::string(ToString(stage)) + "` is not implemented yet. " + detail);
}

} // namespace CaseCommon
